# Generated by Django 5.0.1 on 2024-02-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='values',
            name='lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='values',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
